name: Docker

on:
  push:
    branches: [ master ]
    tags: ['*']
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build development
      uses: docker/build-push-action@v1.0.1
      with:
        repository: sandtank-dev
        tags: latest
        # Need docker build context to be "." for this one
        dockerfile: docker/development/Dockerfile
        add_git_labels: true
        push: false

    - name: Build runtime
      uses: docker/build-push-action@v1.0.1
      with:
        repository: sandtank-runtime
        tags: latest
        path: docker/runtime
        add_git_labels: true
        push: false

    - name: Create Docker Tag
      # If a git tag was pushed, use the git tag for the docker tag
      # Otherwise, use "latest"
      run: |
        if [[ $REF == refs/tags/* ]]
        then
          echo "::set-env name=DOCKER_TAG::${REF#'refs/tags/'}"
        else
          echo "::set-env name=DOCKER_TAG::latest"
        fi
      env:
        REF: ${{ github.ref }}

    - name: Build and push web service
      uses: docker/build-push-action@v1.0.1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: hydroframe/sandtank
        tags: ${{ env.DOCKER_TAG }}
        path: docker/web
        add_git_labels: true
        # Do not push for pull requests. Only after they have been merged.
        push: ${{ github.event_name == 'push' }}
